---
- name: Download the Go tarball
  get_url:
    url: "{{ go_download_location }}"
    dest: /usr/local/src/{{ go_tarball }}
    checksum: "{{ go_tarball_checksum }}"

- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

- name: Remove old installation of Go
  file:
    path: /usr/local/go
    state: absent
  when: go_version|failed or go_version.stdout != go_version_target

- name: Extract the Go tarball if Go is not yet installed or not the desired version
  unarchive:
    src: /usr/local/src/{{ go_tarball }}
    dest: /usr/local
    copy: no
  when: go_version|failed or go_version.stdout != go_version_target

- name: Add the Go bin directory to the PATH environment variable for all users
  copy:
    src: go-bin.sh
    dest: /etc/profile.d

- name: Set GOPATH for all users
  copy:
    src: go-path.sh
    dest: /etc/profile.d
  when: set_go_path

- name: setup service file
  copy:
    src: go-app.service
    dest: /usr/lib/systemd/system/
  become: true

- name: Create the app-directory
  file:
    path: /opt/go-app
    state: directory
    mode: '0755'

- name: Copy deployment file to the server
  copy:
     src: main.go
     dest: /opt/go-app/main.go

- name: Reload service daemon
  shell: systemctl daemon-reload

- name: Start service
  shell: systemctl start go-app
